node {

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Deploy') {
   		sh 'kubectl apply -f struts2.yml'
    }
}